FROM ubuntu:noble

WORKDIR /app

# 安装 ExifTool
RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates libimage-exiftool-perl && \
    rm -rf /var/lib/apt/lists/*

# 由 Docker BuildKit 自动注入（amd64 / arm64）
ARG TARGETARCH

COPY dist/xiaomi-album-syncer-${TARGETARCH} /app/xiaomi-album-syncer

RUN chmod +x /app/xiaomi-album-syncer

# 暴露应用端口
EXPOSE 8080

ENTRYPOINT ["/app/xiaomi-album-syncer"]
