FROM ibm-semeru-runtimes:open-25-jre-noble
WORKDIR /app

# 安装 ExifTool
RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates libimage-exiftool-perl && \
    rm -rf /var/lib/apt/lists/*


# 把 JAR 拷贝到镜像里
ARG JAR_FILE=app.jar
COPY ${JAR_FILE} app.jar

# 暴露应用端口(默认Spring Boot端口)
EXPOSE 8080

# 允许通过环境变量传递JVM参数
# 隐藏 SQLite 的警告信息
ENV JAVA_OPTS="--enable-native-access=ALL-UNNAMED"

# 启动应用
ENTRYPOINT ["sh", "-c", "exec java $JAVA_OPTS -jar app.jar"]
